Rewrite install task
virtool/virtool pull request #1927
Opened 2020-10-14 23:35 UTC by tianshengsui

resolve #1909

2020-10-15 21:42 UTC, igboyes requested changes
One rename.

Why didn't you split the task functions into separate steps when moving to `Task`?

2020-10-15 21:42 UTC, igboyes commented on virtool/hmm/db.py
> +class HmmInstallTask(virtool.tasks.task.Task):
Rename to `HMMInstallTask`.

2020-10-15 21:58 UTC, tianshengsui commented
> One rename.
> 
> Why didn't you split the task functions into separate steps when moving to `Task`?

Because all the code are under the context of ```tempdir```. If I split them into several functions, I think the ```tempdir``` will be closed and removed.

2020-10-15 22:07 UTC, igboyes commented
Okay. That is what I thought.

Can you add the tempdir generation and cleanup to the base `Task` class and make `temp_dir` an attribute on that class? That way the temporary directory is available to all the tasks but is still automatically deleted at the end.

2020-10-15 22:10 UTC, tianshengsui commented
I will do it.

2020-10-20 22:53 UTC, igboyes approved these changes

2020-10-20 22:53 UTC, merged