Added Label Editor to Sample Detail Page
virtool/virtool pull request #1997
Opened 2020-12-01 22:21 UTC by ColeVoelpel

Let me know if there is any UI changes you want. I left the create label section open by default on the modal to fill it out but that is an easy change if necessary.

2021-01-08 17:51 UTC, igboyes requested changes

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/ColorSelector.js
> +export const StyledInput = styled(Input)`
`ColorSelectorInput`

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/ColorSelector.js
> +export const StyledColorButton = styled(Button)`
`ColorSelectorButton`

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/ColorSelector.js
> +        this.state = getInitialState(this.props);
You are managing state here and in your parent component.

Keep the state in `CreateLabel`. The `ColorSelector` component should take the color value as a prop and pass events back to `CreateLabel` using your `onColorChange` prop.

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelEditor.js
> +export const StyledTable = styled(Table)`
Only use `table` elements for actual tables. You can solve this layout problem better with [flex box](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +    onRemove = (id, name) => {
`handleRemove()`

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +    onEdit = (id, name, color, description) => {
`handleEdit()`

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +        const id = this.state.id;
Use object spread.

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +    name: sate.name,
Not `sate`.

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +export const StyledIcon = styled(Icon)`
`LabelItemIcon`

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +`;
I don't think these need to be exported.

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +`;
Does not need to be exported.

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +    padding: 0px 8px;
When CSS value is `0`, omit units.

```css
padding: 0 8px;
```

2021-01-08 17:51 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/LabelItem.js
> +export const StyledLabel = styled(Label)`
`Styled` prefix for components is only used when it is the top-level component in another component. This should be renamed. Something like `LabelItemExample`.

2021-01-08 18:17 UTC, igboyes commented on client/src/js/samples/components/LabelEditor/CreateLabel.js
> +const getInitialState = ({ labelName, color, description, errorName, errorColor }) => ({
Do not need to derive state from props. Form will be empty initially.

`constructor` method is not needed for class.

2021-01-13 20:50 UTC, ColeVoelpel commented
The only change I could not do was the "createLables" -> "create" name change. It is sharing the same api file with the samples which has a "create" already for creating samples.

2021-01-15 23:00 UTC, igboyes requested changes
Please move all label code to new top-level module at `src/js/labels`.

If you have no children for a component call it without a closing tag:
```jsx
<div>
  <Input name="test" value="Foo" />
</div>
```

Instead of:
```jsx
<div>
  <Input name="test" value="Foo"></Input>
</div>
```

2021-01-29 17:40 UTC, igboyes commented
Replaced by #2074

2021-01-29 17:40 UTC, closed without merging