Support upload of analysis files
virtool/virtool pull request #2100
Opened 2021-02-17 19:18 UTC by jakeale

- Implement SQL model for `analysis_files`, a table to store analysis result files
- Support uploading at `POST /api/analyses/:id/files`
- Support downloading at `GET /api/analyses/:id/files/:id`
- Attach detailed file information from `analysis_files` SQL table to `GET /api/analyses/:id` calls

2021-02-18 00:14 UTC, igboyes commented
I think the first three commits in this PR are from another branch.

2021-02-18 00:24 UTC, jakeale commented
> I think the first three commits in this PR are from another branch.

Yes I think I messed up a rebase. It looks like they can be safely dropped if you don't mind another rebase.

2021-02-18 20:15 UTC, igboyes requested changes

2021-02-18 20:15 UTC, igboyes commented on tests/analyses/test_api.py
> +async def test_download_file(exists, files, spawn_client, snapshot, tmpdir):
Can you figure out how to test that the correct file is actually written?

2021-02-18 20:15 UTC, igboyes commented on virtool/analyses/api.py
> +        logger.debug(f"Upload aborted: {file_id}")
Change to "Analysis file upload" to differentiate from user uploads.

2021-02-18 20:15 UTC, igboyes commented on virtool/analyses/utils.py
> +async def attach_analysis_files(pg: AsyncEngine, analysis_id: str) -> List[Dict]:
I don't think this is unit tested.

2021-02-22 17:44 UTC, igboyes requested changes

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/api.py
> +    name_on_disk = analysis_file["name_on_disk"]
You need to refer to the files by their `id`, not `name_on_disk`.

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/api.py
> +    if not analysis_file:
If this happens it is a bug. We should not handle it and blame it on the client (`4**` status).

Clients should also not receive messages about implementation details of the application such as problems with the backing SQL database. The API is meant to abstract away these details.

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/api.py
> +    })
Use `$push`. If there are two requests being handled at the same time (ie. the workflow is concurrently uploading two files), rewriting the `files` field could cause a serious bug.

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/db.py
> +async def create_row(pg: AsyncEngine, analysis_id: str, analysis_format: str, name: str) -> Dict[str, any]:
The naming of these is going to clash with the `Analysis` model when it is eventually created.

I think we should move the analysis file code into a new module: `virtool.analyses.files`. Also, change these function names to something like `create_analysis_file`.

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/db.py
> +    :return:
Describe `:return:`.

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/models.py
> +    SQL table to store new analysis files
Is a model, not a table.

2021-02-22 17:44 UTC, igboyes commented on virtool/analyses/utils.py
> +            files.append(result.to_dict())
```py
async with AsyncSession(pg) as session:
    results = (await session.execute(select(AnalysisFile).filter_by(analysis=analysis_id))).scalars().all()

return [result.to_dict() for result in results]
```

2021-02-22 17:44 UTC, igboyes commented on virtool/uploads/utils.py
> +        file_path.parent.mkdir()
Must run in thread to prevent filesystem blocking.

2021-02-22 21:07 UTC, igboyes approved these changes

2021-02-22 21:09 UTC, merged