Add subtraction finalization endpoint
virtool/virtool pull request #2118
Opened 2021-02-25 00:03 UTC by tianshengsui

[ch424]

2021-02-25 16:28 UTC, igboyes requested changes
Thanks. One more thing.

2021-02-25 17:42 UTC, tianshengsui commented
@igboyes You didn't select any code.

2021-02-25 17:47 UTC, igboyes requested changes

2021-02-25 17:47 UTC, igboyes commented on virtool/subtractions/api.py
> +    })
Return `409` if subtraction has already been finalized. Message: _Subtraction has already been finalized_.

2021-02-25 17:47 UTC, igboyes commented
> @igboyes You didn't select any code.

I think I typed my comment, but didn't save. Added review.

2021-02-26 16:59 UTC, igboyes approved these changes

2021-02-26 16:59 UTC, merged