Split up virtool.app.on_shutdown
virtool/virtool pull request #2209
Opened 2021-04-01 19:34 UTC by jakeale

* Split up into separate tasks in `virtool.shutdown`
* Add tasks to `virtool.app.create_app`

2021-04-01 20:15 UTC, igboyes requested changes

2021-04-01 20:15 UTC, igboyes commented on virtool/shutdown.py
> +        pass
Combine to mirror `init_executors`.
```suggestion
async def exit_executors(app: aiohttp.web.Application):
    """
    Attempt to close the `ThreadPoolExecutor` and `ProcessPoolExecutor`.

    :param app: the application object
    """
    try:
        app["executor"].shutdown(wait=True)
    except KeyError:
        pass
    try:
        app["process_executor"].shutdown(wait=True)
    except KeyError:
        pass
```

2021-04-01 20:51 UTC, jakeale commented
Just took another look at `virtool.startup` and noticed `init_db` and `init_postgres`. Do you want these to be manually shut down and logged as well?

2021-04-01 21:02 UTC, igboyes commented
> Just took another look at `virtool.startup` and noticed `init_db` and `init_postgres`. Do you want these to be manually shut down and logged as well?

I'm not sure. Can you do some research on `motor` and `sqlalchemy` to see if this is really necessary?

2021-04-01 21:24 UTC, jakeale commented
> > Just took another look at `virtool.startup` and noticed `init_db` and `init_postgres`. Do you want these to be manually shut down and logged as well?
> 
> I'm not sure. Can you do some research on `motor` and `sqlalchemy` to see if this is really necessary?

I could not find the best practices with `motor` but I found this in the `sqlalchemy` docs:

> Valid use cases for calling Engine.dispose() include:
> 
> * When a program wants to release any remaining checked-in connections held by the connection pool and expects to no longer be connected to that database at all for any future operations.
> 
> * When a program uses multiprocessing or fork(), and an Engine object is copied to the child process, Engine.dispose() should be called so that the engine creates brand new database connections local to that fork. Database connections generally do not travel across process boundaries.
> 
> * Within test suites or multitenancy scenarios where many ad-hoc, short-lived Engine objects may be created and disposed.

If there are any open database connections at the time of garbage collection, the `Engine` will keep them alive. Can't immediately think of a case where this could happen.

https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=dispose#engine-disposal

2021-04-06 21:24 UTC, igboyes approved these changes

2021-04-06 21:25 UTC, merged

2021-04-06 21:26 UTC, igboyes commented
Thanks for checking into that @jakeale!