Add JWT refresh tokens
virtool/virtool pull request #2387
Opened 2021-09-13 17:59 UTC by eroberts9789

Add JWT to Virtool API and write tests

2021-09-13 21:34 UTC, igboyes requested changes

2021-09-13 21:34 UTC, igboyes commented on tests/users/test_jwt.py
> +        assert decoded == {
Use double quotes.

2021-09-13 21:34 UTC, igboyes commented on virtool/users/jwt.py
> +async def create_reset_code_with_jwt():
What is this for? Should be removed if unused.

2021-09-13 21:34 UTC, igboyes commented on virtool/users/jwt.py
> +        decode(refresh_token, REFRESH_SECRET + str(password), algorithms=JWT_ALGORITHM)
```suggestion
        decode(refresh_token, f"{REFRESH_SECRET}{str(password)}", algorithms=JWT_ALGORITHM)
```

2021-09-13 22:41 UTC, eroberts9789 commented on virtool/users/jwt.py
> +        "ip": ip
I can look into it further if that would be helpful but I was just including the same info in the access tokens as is kept in the session. I'm not really sure what it's used for in the sessions atm but I didn't want to rule it out.

2021-09-28 16:20 UTC, igboyes commented
Closing for now.

2021-09-28 16:20 UTC, closed without merging