chore: add auto-doc for jobs API endpoints
virtool/virtool pull request #2598
Opened 2022-06-22 21:03 UTC by buddy326

2022-06-22 21:52 UTC, igboyes requested changes

2022-06-22 22:00 UTC, buddy326 commented on virtool/jobs/api.py
>  async def get(req):
would you like me to do that for all methods with both a @routes.jobs_api.[HTTP METHOD] decorator and a @routes.[HTTP METHOD] decorator?

2022-06-22 22:48 UTC, igboyes commented on virtool/jobs/api.py
>  async def get(req):
No. Just this one ATM.

2022-06-23 22:51 UTC, igboyes approved these changes

2022-06-23 22:51 UTC, merged