fix: ian's fixes to history api
virtool/virtool pull request #2647
Opened 2022-08-10 17:47 UTC by buddy326

2022-08-12 01:30 UTC, buddy326 commented
Not sure if i should be raising `ResourceNotFoundError()` from history.data.get() or just return None lilke Im doing right now. Thats what the get() method was doing in history.db. i'm sure some things could get changed so just let me know how i can improve it.

2022-08-12 16:19 UTC, igboyes commented
Yes. Raise the error instead of returning `None`.

Are you going to work on `revert()`?

2022-08-12 16:29 UTC, buddy326 commented
ok, and yes I worked on it a little yesterday but wanted clarification on the get() first too.

2022-08-12 17:21 UTC, igboyes requested changes
Just a few things. Excellent work!

2022-08-12 17:21 UTC, igboyes commented on virtool/history/data.py
> +            return document
```suggestion
            return await apply_transforms(
                virtool.utils.base_processor(document),
                [AttachUserTransform(self._db), DiffTransform(self.data_path)],
            )
```

2022-08-12 17:21 UTC, igboyes commented on virtool/history/data.py
> +                await self._db.otus.delete_one({"_id": otu_id})
Flip this so it is `if patched is None:`.

2022-08-12 23:35 UTC, igboyes reviewed
I'll merge once you fix Deepsource issues.

2022-08-15 16:53 UTC, igboyes approved these changes

2022-08-15 16:56 UTC, merged