chore: add tasks data layer
virtool/virtool pull request #2680
Opened 2022-09-06 20:25 UTC by ReeceHoffmann

Changes

 - Converts functions from tasks/pg.py to be part of new tasks datalayer.
   - Updates previous uses of tasks/pg.py to fetch and use datalayer from `app`
 - Updates tests as needed to check for correct datatypes

2022-09-06 22:07 UTC, igboyes requested changes

2022-09-06 22:07 UTC, igboyes commented on virtool/tasks/data.py
> +    async def find(self) -> list:
```suggestion
    async def find(self) -> List[Task]:
```

2022-09-06 22:07 UTC, igboyes commented on virtool/tasks/data.py
> +        return TaskModel(**document)
Use blank lines to break up ideas.

```suggestion
        task = Task(
            complete=False,
            context=context or {},
            step=task_class.task_type,
            count=0,
            created_at=virtool.utils.timestamp(),
            progress=0,
            type=task_class.task_type,
        )
        
        async with AsyncSession(self._pg) as session:
            session.add(task)
            await session.flush()
            document = task.to_dict()
            await session.commit()
            
        return TaskModel(**document)
```

2022-09-07 16:03 UTC, ReeceHoffmann commented
Force pushed to rebase onto main

2022-09-09 19:09 UTC, igboyes requested changes

2022-09-09 19:09 UTC, igboyes commented on virtool/analyses/data.py
> +            await self._tasks_data.add(
```suggestion
            await self.data.tasks.add(
```
Remove `self._tasks_data` as well.

### Explanation
https://github.com/virtool/virtool/blob/fdb5695bfe273ef346b7d55cfe116a7372486152/virtool/data/piece.py#L10
https://github.com/virtool/virtool/blob/fdb5695bfe273ef346b7d55cfe116a7372486152/virtool/data/layer.py#L41

2022-09-09 19:09 UTC, igboyes commented on virtool/blast/data.py
> +        self._tasks_data = tasks_data
Use `self.data` like in analyses. You will have to call `bind_layer`. That is not in `__post_init__` yet.

Do this for all further situations.

2022-09-09 19:09 UTC, igboyes commented on virtool/references/api.py
> +    task = await get_data_from_req(req).tasks.add(UpdateRemoteReferenceTask, context=context)
Let's take the opportunity to change this from `add` to `create` to match the rest of the data layer.

2022-09-09 19:09 UTC, igboyes commented on virtool/startup.py
> +    await get_data_from_app(app).tasks.add(CleanReferencesTask)
Can just call `get_data_from_app` once here and store the reference.

2022-09-09 19:09 UTC, igboyes commented on virtool/tasks/data.py
> +    async def add(self, task_class: Type[Task], context: dict = None):
### Naming
Rename `add()` to `create()` to realign with rest of data layer.

### Use `Optional`
```suggestion
    async def add(self, task_class: Type[Task], context: Optional[Dict] = None):
```

https://docs.python.org/3/library/typing.html#typing.Optional

2022-09-12 22:18 UTC, igboyes approved these changes

2022-09-12 22:18 UTC, merged