chore: auto doc reference endpoints
virtool/virtool pull request #2683
Opened 2022-09-09 19:52 UTC by ryanfang5

2022-09-09 19:57 UTC, ryanfang5 commented
I am not sure that the example responses for "updates" are correct.

2022-09-12 17:40 UTC, igboyes requested changes

2022-09-12 17:40 UTC, igboyes commented on tests/references/test_api.py
> -        await resp_is.invalid_input(
Missing check of status code. I suggest having two error tests like `400_duplicates`, `400_invalid_input`.

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +    async def get(self) -> Union[r200[ReferenceResponse], r404]:
This should return `403` as well if the client doesn't have read permission on the reference.

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Get OTUs of a reference
```suggestion
        Find OTUs.
        
        Finds OTUs by name or abbreviation. Results are paginated.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        List indexes of the reference.
```suggestion
        List indexes.
        
        Retrieves a paginated list of indexes that have been created for the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        List groups of the reference.
```suggestion
        List groups.
        
        Lists all groups that have access to the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Allow groups to view, use and modify the reference.
```suggestion
        Add a group.
        
        Adds a group to the reference. Groups can view, use, and modify the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Get a specific group of the reference
```suggestion
        Get a group.
        
        Retrieves the details of a group that has access to the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Allow users to view, use and modify the reference.
Update to match docstring for groups.

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Edit the reference rights of a specific user.
Update to match docstring for groups.

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Remove the user from the reference.
Update to match docstring for groups.

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Edit the reference rights of a specific group.
```suggestion
        Update a group.
        
        Updates the access rights a group has on the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        List history of the reference.
```suggestion
        List history.
        
        Retrieves a paginated list of changes made to OTUs in the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Update the reference using the linked remote reference.
```suggestion
        Update a reference.
        
        Updates the reference to the last version of the linked remote reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        List all updates made to the reference.
```suggestion
        List updates.
        
        Lists all updates made to the reference.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/api.py
> +        Get the latest update from GitHub and return it.
```suggestion
        Get latest update.
        
        Retrieves the latest remote reference update from GitHub.
```

2022-09-12 17:40 UTC, igboyes commented on virtool/references/oas.py
> +from typing import Optional, Union, List
Excellent use of validators in this module. But... we do need to test them. Add a `test_oas.py` to make sure that model implementing the validators work as expected.

2022-09-12 19:57 UTC, ryanfang5 commented
I also added Permission.create_ref to the post method for /refs. However, I noticed that this method also requires Permission.upload_file but only when importing from a file. I am not sure how to implement this since the permissions are checked before the method is run.

2022-09-12 21:41 UTC, igboyes requested changes

2022-09-12 21:41 UTC, igboyes commented on tests/references/test_oas.py
> +            mock_create_reference_schema.update({"data_type": "bad type"})
Put the update dictionary as the pytest parameter instead. This test can be heavily simplified.

2022-09-12 21:44 UTC, igboyes commented
> I also added Permission.create_ref to the post method for /refs. However, I noticed that this method also requires Permission.upload_file but only when importing from a file. I am not sure how to implement this since the permissions are checked before the method is run.

Are you sure? I don't see that in the existing code. I believe the upload is executed in a separate request before the creation request is made.

2022-09-12 22:54 UTC, ryanfang5 commented
> > I also added Permission.create_ref to the post method for /refs. However, I noticed that this method also requires Permission.upload_file but only when importing from a file. I am not sure how to implement this since the permissions are checked before the method is run.
> 
> Are you sure? I don't see that in the existing code. I believe the upload is executed in a separate request before the creation request is made.

My mistake, you are right.

2022-09-12 23:06 UTC, igboyes commented
> My mistake, you are right.

Perfect! Can you resolve conflict and I will merge?

2022-09-13 18:00 UTC, igboyes approved these changes

2022-09-13 18:00 UTC, merged