feat: add endpoints for managing users' app permissions
virtool/virtool pull request #2761
Opened 2022-12-14 23:25 UTC by ryanfang5

2022-12-16 00:38 UTC, igboyes requested changes
Please add a test that shows what happens when an invalid permission name is provided in the URL.

2022-12-19 21:13 UTC, igboyes requested changes
I discussed this with @ReeceHoffmann and we'd like to return a list of objects from the API like:
```
[
  {"id": "create"sample"},
  {"id": "create_subtraction"}
]
```
It will be easier to add additional fields like `description` or `name` later if needed. Sound good?

Don't change the authz client to do this. Do it in the request handler.

2022-12-20 00:51 UTC, ryanfang5 commented
> I discussed this with @ReeceHoffmann and we'd like to return a list of objects from the API like:
> 
> ```
> [
>   {"id": "create"sample"},
>   {"id": "create_subtraction"}
> ]
> ```
> 
> It will be easier to add additional fields like `description` or `name` later if needed. Sound good?
> 
> Don't change the authz client to do this. Do it in the request handler.

Do you mean a list of objects that the user has access to, or did you just want me to add {"id": permission} in the current list permissions response? If it is the former, I'm not sure why this wouldn't be implemented in the authz client and called in another endpoint.

2022-12-20 21:14 UTC, igboyes approved these changes

2022-12-20 21:15 UTC, merged