feat: add administrators task to promote users
virtool/virtool pull request #2831
Opened 2023-03-15 16:57 UTC by ryanfang5

2023-03-15 23:43 UTC, igboyes requested changes

2023-03-15 23:43 UTC, igboyes commented on tests/administrators/test_tasks.py
> +    async with mongo.create_session() as session:
Don't need a session for this.

They are slower and data consistency doesn't matter so much for tests.

2023-03-15 23:43 UTC, igboyes commented on virtool/administrators/data.py
> +        async with self._db.create_session() as session:
Session doesn't add anything here. You are not modifying MongoDB, which is where as transaction is important.

2023-03-15 23:43 UTC, igboyes commented on virtool/administrators/data.py
> +            ):
You can use `users.distinct("_id", {"administrator": True})` here to be more efficient.

2023-03-15 23:43 UTC, igboyes commented on tests/administrators/test_tasks.py
> +        await data_layer.administrators._authorization_client.list_administrators()
I think it's better to use `data_layer.administrators.find` here. That way we're testing the same interface that tasks is touching.

2023-03-15 23:56 UTC, ReeceHoffmann commented on virtool/startup.py
> +    await tasks_data.create_periodically(PromoteAdministratorsTask, 600)
No need to add this here, this method of spawning tasks will be deprecated and removed in a later version.

2023-03-16 18:27 UTC, igboyes submitted a review, later dismissed

2023-03-21 16:15 UTC, igboyes approved these changes

2023-03-21 16:16 UTC, merged