Markus/vir 1744 set job field on new samples
virtool/virtool pull request #2862
Opened 2023-04-14 23:19 UTC by SnickerDoodlePop

2023-04-18 22:28 UTC, ReeceHoffmann requested changes
Looks like it solves the atomicity problem! Need to tweak how `create_job` is getting access to the data sources it needs though. Looking close

2023-04-20 21:49 UTC, igboyes reviewed
Looking good other than one oddity.

2023-04-20 21:49 UTC, igboyes commented on virtool/jobs/data.py
> +        job_client = copy.copy(self._client)
Why?

2023-04-20 21:52 UTC, SnickerDoodlePop commented on virtool/jobs/data.py
> +        job_client = copy.copy(self._client)
oops, that shouldn't be there

2023-04-24 17:00 UTC, merged