Markus/vir 1791 check virtoolca for reference releases
virtool/virtool pull request #2876
Opened 2023-05-04 20:45 UTC by SnickerDoodlePop

2023-05-08 20:20 UTC, igboyes requested changes
Black formatting does not seem to be working for you. Please resolve.

2023-05-08 20:20 UTC, igboyes commented on tests/references/test_db.py
> +    match status:
This can be simplified to a few `if` statements.

2023-05-08 20:20 UTC, igboyes commented on virtool/references/db.py
> +            updated = format_latest_release(updated)
Do you see a problem with variable naming here?

2023-05-08 21:01 UTC, SnickerDoodlePop commented on virtool/references/db.py
> +    # change below here
Will be removed before merging. Apologies they are still included; these comments are only for myself while working.

2023-05-30 20:53 UTC, igboyes reviewed
Have you run this in Minikube to make sure it works when deployed?

2023-05-31 22:34 UTC, igboyes approved these changes

2023-05-31 22:35 UTC, merged