feat: restrict allowed sequence characters
virtool/virtool pull request #2920
Opened 2023-08-03 21:44 UTC by SnickerDoodlePop

The OTU DataLayer now restricts sequence creation / updating to only contain characters in [ATCGRYKM \n]

2023-08-03 22:14 UTC, SnickerDoodlePop commented
Utils function `validate_sequence` was replaced with a functor `ValidateSequence` to take advantage of Pydantic `BaseModel`.

2023-08-08 21:38 UTC, igboyes requested changes
Do this at the request handler by modifying the request model `CreateSequenceRequest`.

https://github.com/virtool/virtool/blob/4d3d505fcb83602a942f5535a606928b16469c00/virtool/otus/api.py#L363

https://github.com/virtool/virtool/blob/4d3d505fcb83602a942f5535a606928b16469c00/virtool/otus/oas.py#L35

2023-08-09 18:30 UTC, igboyes requested changes
Apply requested changes in both locations.

2023-08-09 19:41 UTC, igboyes approved these changes

2023-08-09 19:42 UTC, merged