refactor: merge `http.errors` with `api.response`
virtool/virtool pull request #2926
Opened 2023-08-11 20:25 UTC by SnickerDoodlePop

2023-08-11 20:25 UTC, SnickerDoodlePop commented
Docstrings are NOT yet written.

2023-08-17 20:14 UTC, ReeceHoffmann requested changes
Code restructure looks good, added some docstring suggestions. Feel free to stray from the suggestions. Write additional docstrings for the custom exceptions

2023-08-17 20:14 UTC, ReeceHoffmann commented on virtool/api/response.py
> +    :param handler:
```suggestion
    Request handling middleware for converting HTTP exceptions into HTTP responses

    :param req: the incoming request
    :param handler: the next middleware to be executed
```

2023-08-18 17:50 UTC, ReeceHoffmann requested changes

2023-08-23 17:26 UTC, igboyes requested changes

2023-08-23 17:26 UTC, igboyes commented on virtool/api/response.py
> +errors to the client.
```suggestion
HTTP error exceptions and middleware for reformatting and reporting
errors to the client.
```

2023-08-23 17:26 UTC, igboyes commented on virtool/api/response.py
> +    to the client.
* How is it used?
  > Raising this exception during request handling immediately returns a `403` (Insufficient Rights) response to the client.
* "Reusable" doesn't have much meaning here.
* Please use this wording for the other docstrings.

2023-08-23 17:26 UTC, igboyes commented on virtool/api/response.py
> +async def middleware(req: web.Request, handler: Callable):
Use `from` imports where this is imported.
```suggestion
async def error_middleware(req: web.Request, handler: Callable):
```

2023-08-23 17:26 UTC, igboyes commented on virtool/api/response.py
> +        return resp
```suggestion
        return await handler(req)
```

2023-08-23 17:26 UTC, igboyes commented on virtool/api/response.py
> +    Request handling middleware for converting HTTP exceptions into HTTP responses.
There is no type of middleware other than "request handling" in the application.
```suggestion
    Middleware for converting HTTP exceptions into HTTP responses.
    
    Catches any `HTTPException` raised during request handling and returns a response with the appropriate status code and JSON body.
```

2023-08-23 18:58 UTC, igboyes approved these changes

2023-08-23 19:49 UTC, merged