refactor: remove job rights
virtool/virtool pull request #2934
Opened 2023-08-24 20:56 UTC by SnickerDoodlePop

>remove class definitions for `JobRights` and `JobRightsDomain`
>replace occurences of `JobRights` with `dict`
>update snapshots to reflect absent job rights

2023-08-24 21:09 UTC, SnickerDoodlePop commented
Deepsource is complaining about an async method being overridden as non-async; I am ignoring this.

2023-08-29 19:06 UTC, igboyes requested changes

2023-08-29 19:06 UTC, igboyes commented on virtool/http/client.py
> +    def __init__(self, job_id, rights: dict):
Is `rights` used for anything in `JobClient` now? It should be removed if not.

2023-08-29 19:06 UTC, igboyes commented on virtool/jobs/data.py
> +        rights: dict,
Remove argument. It is always going to be an empty dict.

2023-08-29 19:06 UTC, igboyes commented on virtool/jobs/db.py
> +        "rights": rights,
Remove argument. It is never going to be a non-empty dict.
```suggestion
        "rights": {},
```

2023-08-29 20:59 UTC, igboyes approved these changes

2023-08-29 21:00 UTC, merged