Matthewcurtis1999/vir 1878 sample creation tests
virtool/virtool pull request #2964
Opened 2023-10-12 17:19 UTC by mattcurts

2023-10-18 19:22 UTC, igboyes requested changes
Thanks. Please also update to use your snapshot extension instead of excluding timestamps from consideration.

2023-10-18 19:22 UTC, igboyes commented on tests/samples/test_api.py
> +        async with AsyncSession(data_layer.samples._pg) as session:
Just access `pg` directly. It is much clearer than diving through the private attributes of the data layer.

2023-10-18 19:22 UTC, igboyes commented on tests/samples/test_api.py
> +        ).upload
Doing assertions against databases should be in data layer tests. Am I missing something here?

2023-10-19 22:58 UTC, mattcurts commented
Needed to do the force push because I servery messed up the merge above. the last 7 commits were made on a new branch off of main to ensure there would not be merge issues.

2023-10-26 18:14 UTC, igboyes requested changes

2023-10-26 18:14 UTC, igboyes commented on tests/samples/test_data.py
> +    assert not (await get_row_by_id(data_layer.samples._pg, SQLSampleReads, 1)).upload
* This is a mash-up of API and DL testing. You should be directly calling the data layer, not using `client`.
* Changes to the database are not verified.

2023-10-26 18:14 UTC, igboyes commented on tests/samples/test_api.py
> +        await resp.json()
?

2023-10-26 18:14 UTC, igboyes commented on tests/samples/test_data.py
> +@pytest.mark.datatest
I don't believe this is used anywhere else.

2023-10-26 18:14 UTC, igboyes commented on tests/samples/test_data.py
> +    Test that sample can be finalized using the Jobs API.
This is a data layer test.

2023-11-27 20:45 UTC, igboyes requested changes

2023-11-27 20:45 UTC, igboyes commented on tests/samples/test_data.py
> +async def test_finalize(
Test needs to be improved.

2023-12-08 19:45 UTC, igboyes approved these changes

2023-12-08 19:46 UTC, merged