Matthewcurtis1999/vir 1904 attributeerror nonetype object has no attribute pop
virtool/virtool pull request #2987
Opened 2023-12-08 18:43 UTC by mattcurts

Added return type hints to all functions that have @emits, and I think the issue is that ``get_json()`` which gets assigned to ``received`` is a shortcut for ``get()`` is either the message received or None signifying that the channel has been unsubscribed and no more messages will be received.

Added a logging message and then subscribe to the events channel before continuing in the loop, waiting for the next event.

https://aioredis.readthedocs.io/en/v1.3.0/api_reference.html

2023-12-08 20:03 UTC, mattcurts commented
no clue why CI is flipping the order of test snapshot

2024-01-16 20:26 UTC, igboyes requested changes
The `emit` function needs to avoid ever putting `None` in the queue. Update this function so it logs a warning and does nothing if `None` is received.

2024-01-16 20:26 UTC, igboyes commented on virtool/data/events.py
> +
Remove this. We are already handling `ChannelClosedError` more rigourously below.

This problem here is that `None` is being put in the queue. Update the `emit` function such that it avoids ever putting `None` in the queue. Log a warning if it is attempted so we can fix the problem.

2024-01-17 22:27 UTC, igboyes requested changes

2024-01-17 22:27 UTC, igboyes commented on virtool/data/events.py
> +
Need an `else` here so that nothing is emitted in warning case.

2024-01-18 22:12 UTC, igboyes approved these changes

2024-01-18 22:14 UTC, merged