Matthewcurtis1999/vir 1905 dont finalize an already finalized sample
virtool/virtool pull request #3001
Opened 2024-01-02 21:43 UTC by mattcurts

2024-01-04 17:09 UTC, igboyes requested changes
Please closely review changes to snapshots.

2024-01-04 17:09 UTC, igboyes commented on tests/samples/test_data.py
> +        pass
Use `pytest.raises`.

2024-01-12 18:31 UTC, mattcurts commented
The Artifacts, Reads, and subtractions missing are intentional, as I am using a simpler fixture that doesn't have those attached and has ``ready`` set to false to ensure that we can test that it gets updated and that we are stopped when trying to finalize it when ``ready`` is true.

2024-01-16 19:22 UTC, igboyes approved these changes

2024-01-16 20:16 UTC, merged